#!/bin/bash

ip link set dev eth0 up 
ip addr add 192.168.188.193/25 dev eth0
ip link set dev eth1 up 
ip addr add 101.3.3.131/25 dev eth1
echo 1 > /proc/sys/net/ipv4/ip_forward

ip r a default via 101.3.3.129

service isc-dhcp-server start 
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE


#Filtrage: Refuser tous les traffics
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#Autoriser le ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

#Autoriser DHCP
iptables -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT

#Autoriser DNS
iptables -t filter -A FORWARD -d 101.3.3.1/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 101.3.3.1/27 -p udp --sport 53 -j ACCEPT

# Autoriser HTTP
iptables -t filter -A FORWARD -d 101.3.3.4/27 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 101.3.3.4/27 -p tcp --sport 80 -j ACCEPT
