#!/bin/bash

ip link set dev eth0 up 
ip addr add 101.3.3.33/27 dev eth0
ip link set dev eth1 up 
ip addr add 101.3.3.2/27 dev eth1
# echo 1 > /proc/sys/net/ipv4/ip_forward

# Bloquer toutes les requêtes sauf celles filtrées
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Authoriser ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Autoriser la mise en place des routes 
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

#Autoriser DNS
iptables -t filter -A FORWARD -d 101.3.3.1/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 101.3.3.1/27 -p udp --sport 53 -j ACCEPT

# Autoriser HTTP
iptables -t filter -A FORWARD -d 101.3.3.4/27 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 101.3.3.4/27 -p tcp --sport 80 -j ACCEPT
